// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"time"
)

// Agency defines model for agency.
type Agency struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus        *int       `json:"agencyStatus,omitempty"`
	CountryCode         *int       `json:"countryCode,omitempty"`
	CreatedAt           *time.Time `json:"createdAt,omitempty"`
	Id                  *int64     `json:"id,omitempty"`
	Name                *string    `json:"name,omitempty"`
	NationalPhoneNumber *string    `json:"nationalPhoneNumber,omitempty"`
	PlatformId          *int64     `json:"platformId,omitempty"`
	PlatformName        *string    `json:"platformName,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyAddResponse defines model for agencyAddResponse.
type AgencyAddResponse struct {
	Code      *int    `json:"code,omitempty"`
	Data      *Id     `json:"data,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencyBatchUpdateRequest defines model for agencyBatchUpdateRequest.
type AgencyBatchUpdateRequest struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus        *int         `json:"agencyStatus,omitempty"`
	CountryCode         *int         `json:"countryCode,omitempty"`
	CreatedAt           *time.Time   `json:"createdAt,omitempty"`
	Id                  *int64       `json:"id,omitempty"`
	Name                *string      `json:"name,omitempty"`
	NationalPhoneNumber *string      `json:"nationalPhoneNumber,omitempty"`
	PlatformId          *int64       `json:"platformId,omitempty"`
	PlatformName        *string      `json:"platformName,omitempty"`
	Query               *AgencyQuery `json:"query,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyBatchUpdateResponse defines model for agencyBatchUpdateResponse.
type AgencyBatchUpdateResponse struct {
	Code      *int                    `json:"code,omitempty"`
	Data      *map[string]interface{} `json:"data,omitempty"`
	Message   *string                 `json:"message,omitempty"`
	RequestId *string                 `json:"requestId,omitempty"`
	Success   *bool                   `json:"success,omitempty"`
}

// AgencyGetResponse defines model for agencyGetResponse.
type AgencyGetResponse struct {
	Code      *int      `json:"code,omitempty"`
	Data      *[]Agency `json:"data,omitempty"`
	Message   *string   `json:"message,omitempty"`
	RequestId *string   `json:"requestId,omitempty"`
	Success   *bool     `json:"success,omitempty"`
}

// AgencyPageRequest defines model for agencyPageRequest.
type AgencyPageRequest struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus        *int       `json:"agencyStatus,omitempty"`
	CountryCode         *int       `json:"countryCode,omitempty"`
	CreatedAt           *time.Time `json:"createdAt,omitempty"`
	CreatedAtFrom       *time.Time `json:"createdAtFrom,omitempty"`
	CreatedAtTo         *time.Time `json:"createdAtTo,omitempty"`
	Id                  *int64     `json:"id,omitempty"`
	IdIn                *[]int64   `json:"idIn,omitempty"`
	Name                *string    `json:"name,omitempty"`
	NationalPhoneNumber *string    `json:"nationalPhoneNumber,omitempty"`
	PageCurrent         *int       `json:"pageCurrent,omitempty"`
	PageSize            *int       `json:"pageSize,omitempty"`
	PlatformId          *int64     `json:"platformId,omitempty"`
	PlatformName        *string    `json:"platformName,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAtFrom      *time.Time `json:"updatedAtFrom,omitempty"`
	UpdatedAtTo        *time.Time `json:"updatedAtTo,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyPageResponse defines model for agencyPageResponse.
type AgencyPageResponse struct {
	Code *int `json:"code,omitempty"`
	Data *struct {
		Current *int64    `json:"current,omitempty"`
		Pages   *int64    `json:"pages,omitempty"`
		Records *[]Agency `json:"records,omitempty"`
		Size    *int64    `json:"size,omitempty"`
		Total   *int64    `json:"total,omitempty"`
	} `json:"data,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencyPlan defines model for agencyPlan.
type AgencyPlan struct {
	AgencyId   *int64  `json:"agencyId,omitempty"`
	AgencyName *string `json:"agencyName,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`

	// Discount in percentage
	Discount *float32 `json:"discount,omitempty"`
	Id       *int64   `json:"id,omitempty"`
	Name     *string  `json:"name,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int    `json:"planStatus,omitempty"`
	PlatformId   *int64  `json:"platformId,omitempty"`
	PlatformName *string `json:"platformName,omitempty"`
	ReferralCode *string `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyPlanAddResponse defines model for agencyPlanAddResponse.
type AgencyPlanAddResponse struct {
	Code      *int    `json:"code,omitempty"`
	Data      *Id     `json:"data,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencyPlanBatchUpdateRequest defines model for agencyPlanBatchUpdateRequest.
type AgencyPlanBatchUpdateRequest struct {
	AgencyId   *int64  `json:"agencyId,omitempty"`
	AgencyName *string `json:"agencyName,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`

	// Discount in percentage
	Discount *float32 `json:"discount,omitempty"`
	Id       *int64   `json:"id,omitempty"`
	Name     *string  `json:"name,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int             `json:"planStatus,omitempty"`
	PlatformId   *int64           `json:"platformId,omitempty"`
	PlatformName *string          `json:"platformName,omitempty"`
	Query        *AgencyPlanQuery `json:"query,omitempty"`
	ReferralCode *string          `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyPlanBatchUpdateResponse defines model for agencyPlanBatchUpdateResponse.
type AgencyPlanBatchUpdateResponse struct {
	Code      *int                    `json:"code,omitempty"`
	Data      *map[string]interface{} `json:"data,omitempty"`
	Message   *string                 `json:"message,omitempty"`
	RequestId *string                 `json:"requestId,omitempty"`
	Success   *bool                   `json:"success,omitempty"`
}

// AgencyPlanGetByReferralCodeRequest defines model for agencyPlanGetByReferralCodeRequest.
type AgencyPlanGetByReferralCodeRequest struct {
	ReferralCode *string `json:"referralCode,omitempty"`
	UserId       *int64  `json:"userId,omitempty"`
}

// AgencyPlanGetByReferralCodeResponse defines model for agencyPlanGetByReferralCodeResponse.
type AgencyPlanGetByReferralCodeResponse struct {
	Code      *int        `json:"code,omitempty"`
	Data      *AgencyPlan `json:"data,omitempty"`
	Message   *string     `json:"message,omitempty"`
	RequestId *string     `json:"requestId,omitempty"`
	Success   *bool       `json:"success,omitempty"`
}

// AgencyPlanGetResponse defines model for agencyPlanGetResponse.
type AgencyPlanGetResponse struct {
	Code      *int          `json:"code,omitempty"`
	Data      *[]AgencyPlan `json:"data,omitempty"`
	Message   *string       `json:"message,omitempty"`
	RequestId *string       `json:"requestId,omitempty"`
	Success   *bool         `json:"success,omitempty"`
}

// AgencyPlanQuery defines model for agencyPlanQuery.
type AgencyPlanQuery struct {
	AgencyId   *int64  `json:"agencyId,omitempty"`
	AgencyName *string `json:"agencyName,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
	CreatedAtFrom   *time.Time `json:"createdAtFrom,omitempty"`
	CreatedAtTo     *time.Time `json:"createdAtTo,omitempty"`

	// Discount in percentage
	Discount *float32 `json:"discount,omitempty"`
	Id       *int64   `json:"id,omitempty"`
	IdIn     *[]int64 `json:"idIn,omitempty"`
	Name     *string  `json:"name,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int    `json:"planStatus,omitempty"`
	PlatformId   *int64  `json:"platformId,omitempty"`
	PlatformName *string `json:"platformName,omitempty"`
	ReferralCode *string `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAtFrom      *time.Time `json:"updatedAtFrom,omitempty"`
	UpdatedAtTo        *time.Time `json:"updatedAtTo,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyPlanUpdateRequest defines model for agencyPlanUpdateRequest.
type AgencyPlanUpdateRequest struct {
	AgencyId   *int64  `json:"agencyId,omitempty"`
	AgencyName *string `json:"agencyName,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`

	// Discount in percentage
	Discount *float32 `json:"discount,omitempty"`
	Id       *int64   `json:"id,omitempty"`
	Name     *string  `json:"name,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int             `json:"planStatus,omitempty"`
	PlatformId   *int64           `json:"platformId,omitempty"`
	PlatformName *string          `json:"platformName,omitempty"`
	Query        *AgencyPlanQuery `json:"query,omitempty"`
	ReferralCode *string          `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyPlanUpdateResponse defines model for agencyPlanUpdateResponse.
type AgencyPlanUpdateResponse struct {
	Code      *int        `json:"code,omitempty"`
	Data      *AgencyPlan `json:"data,omitempty"`
	Message   *string     `json:"message,omitempty"`
	RequestId *string     `json:"requestId,omitempty"`
	Success   *bool       `json:"success,omitempty"`
}

// AgencyQuery defines model for agencyQuery.
type AgencyQuery struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus        *int       `json:"agencyStatus,omitempty"`
	CountryCode         *int       `json:"countryCode,omitempty"`
	CreatedAt           *time.Time `json:"createdAt,omitempty"`
	CreatedAtFrom       *time.Time `json:"createdAtFrom,omitempty"`
	CreatedAtTo         *time.Time `json:"createdAtTo,omitempty"`
	Id                  *int64     `json:"id,omitempty"`
	IdIn                *[]int64   `json:"idIn,omitempty"`
	Name                *string    `json:"name,omitempty"`
	NationalPhoneNumber *string    `json:"nationalPhoneNumber,omitempty"`
	PlatformId          *int64     `json:"platformId,omitempty"`
	PlatformName        *string    `json:"platformName,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAtFrom      *time.Time `json:"updatedAtFrom,omitempty"`
	UpdatedAtTo        *time.Time `json:"updatedAtTo,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyUpdateRequest defines model for agencyUpdateRequest.
type AgencyUpdateRequest struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus        *int         `json:"agencyStatus,omitempty"`
	CountryCode         *int         `json:"countryCode,omitempty"`
	CreatedAt           *time.Time   `json:"createdAt,omitempty"`
	Id                  *int64       `json:"id,omitempty"`
	Name                *string      `json:"name,omitempty"`
	NationalPhoneNumber *string      `json:"nationalPhoneNumber,omitempty"`
	PlatformId          *int64       `json:"platformId,omitempty"`
	PlatformName        *string      `json:"platformName,omitempty"`
	Query               *AgencyQuery `json:"query,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyUpdateResponse defines model for agencyUpdateResponse.
type AgencyUpdateResponse struct {
	Code      *int    `json:"code,omitempty"`
	Data      *Agency `json:"data,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencyWithPlan defines model for agencyWithPlan.
type AgencyWithPlan struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus *int `json:"agencyStatus,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CountryCode     *int       `json:"countryCode,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`

	// Discount in percentage
	Discount            *float32 `json:"discount,omitempty"`
	Id                  *int64   `json:"id,omitempty"`
	Name                *string  `json:"name,omitempty"`
	NationalPhoneNumber *string  `json:"nationalPhoneNumber,omitempty"`
	PlanId              *int64   `json:"planId,omitempty"`
	PlanName            *string  `json:"planName,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int    `json:"planStatus,omitempty"`
	PlatformId   *int64  `json:"platformId,omitempty"`
	PlatformName *string `json:"platformName,omitempty"`
	ReferralCode *string `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// AgencyWithPlanAddResponse defines model for agencyWithPlanAddResponse.
type AgencyWithPlanAddResponse struct {
	Code *int `json:"code,omitempty"`
	Data *struct {
		AgencyId     *int64 `json:"agencyId,omitempty"`
		AgencyPlanId *int64 `json:"agencyPlanId,omitempty"`
	} `json:"data,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencyWithPlanGetResponse defines model for agencyWithPlanGetResponse.
type AgencyWithPlanGetResponse struct {
	Code      *int              `json:"code,omitempty"`
	Data      *[]AgencyWithPlan `json:"data,omitempty"`
	Message   *string           `json:"message,omitempty"`
	RequestId *string           `json:"requestId,omitempty"`
	Success   *bool             `json:"success,omitempty"`
}

// AgencyWithPlanPageRequest defines model for agencyWithPlanPageRequest.
type AgencyWithPlanPageRequest struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus *int `json:"agencyStatus,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CountryCode     *int       `json:"countryCode,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
	CreatedAtFrom   *time.Time `json:"createdAtFrom,omitempty"`
	CreatedAtTo     *time.Time `json:"createdAtTo,omitempty"`

	// Discount in percentage
	Discount            *float32 `json:"discount,omitempty"`
	Id                  *int64   `json:"id,omitempty"`
	Name                *string  `json:"name,omitempty"`
	NationalPhoneNumber *string  `json:"nationalPhoneNumber,omitempty"`
	OrderByColumn       *string  `json:"orderByColumn,omitempty"`

	// OrderByDirection 1:asc 2:desc
	OrderByDirection *int    `json:"orderByDirection,omitempty"`
	PageCurrent      *int    `json:"pageCurrent,omitempty"`
	PageSize         *int    `json:"pageSize,omitempty"`
	PlanId           *int64  `json:"planId,omitempty"`
	PlanName         *string `json:"planName,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int    `json:"planStatus,omitempty"`
	PlatformId   *int64  `json:"platformId,omitempty"`
	PlatformName *string `json:"platformName,omitempty"`
	ReferralCode *string `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int `json:"registrationMethod,omitempty"`

	// Strategy 1:newest 2:oldest 3:newest active 4:oldest active
	Strategy      *int       `json:"strategy,omitempty"`
	UpdatedAtFrom *time.Time `json:"updatedAtFrom,omitempty"`
	UpdatedAtTo   *time.Time `json:"updatedAtTo,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
}

// AgencyWithPlanPageResponse defines model for agencyWithPlanPageResponse.
type AgencyWithPlanPageResponse struct {
	Code *int `json:"code,omitempty"`
	Data *struct {
		Current *int64            `json:"current,omitempty"`
		Pages   *int64            `json:"pages,omitempty"`
		Records *[]AgencyWithPlan `json:"records,omitempty"`
		Size    *int64            `json:"size,omitempty"`
		Total   *int64            `json:"total,omitempty"`
	} `json:"data,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencyWithPlanQuery defines model for agencyWithPlanQuery.
type AgencyWithPlanQuery struct {
	// AgencyStatus 1:active 2:inactive
	AgencyStatus *int `json:"agencyStatus,omitempty"`

	// CardAssociation 1:visa 2:masterCard 3:AmericanExpress 4:JCB 5:unionPay
	CardAssociation *int       `json:"cardAssociation,omitempty"`
	CountryCode     *int       `json:"countryCode,omitempty"`
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
	CreatedAtFrom   *time.Time `json:"createdAtFrom,omitempty"`
	CreatedAtTo     *time.Time `json:"createdAtTo,omitempty"`

	// Discount in percentage
	Discount            *float32 `json:"discount,omitempty"`
	Id                  *int64   `json:"id,omitempty"`
	Name                *string  `json:"name,omitempty"`
	NationalPhoneNumber *string  `json:"nationalPhoneNumber,omitempty"`
	OrderByColumn       *string  `json:"orderByColumn,omitempty"`

	// OrderByDirection 1:asc 2:desc
	OrderByDirection *int    `json:"orderByDirection,omitempty"`
	PlanId           *int64  `json:"planId,omitempty"`
	PlanName         *string `json:"planName,omitempty"`

	// PlanStatus 1:active 2:inactive
	PlanStatus   *int    `json:"planStatus,omitempty"`
	PlatformId   *int64  `json:"platformId,omitempty"`
	PlatformName *string `json:"platformName,omitempty"`
	ReferralCode *string `json:"referralCode,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int `json:"registrationMethod,omitempty"`

	// Strategy 1:newest 2:oldest 3:newest active 4:oldest active
	Strategy      *int       `json:"strategy,omitempty"`
	UpdatedAtFrom *time.Time `json:"updatedAtFrom,omitempty"`
	UpdatedAtTo   *time.Time `json:"updatedAtTo,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
}

// Id defines model for id.
type Id struct {
	Id *int64 `json:"id,omitempty"`
}

// Platform defines model for platform.
type Platform struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`

	// RegistrationMethod 1:phone 2:email 3:username
	RegistrationMethod *int       `json:"registrationMethod,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// PlatformGetResponse defines model for platformGetResponse.
type PlatformGetResponse struct {
	Code      *int        `json:"code,omitempty"`
	Data      *[]Platform `json:"data,omitempty"`
	Message   *string     `json:"message,omitempty"`
	RequestId *string     `json:"requestId,omitempty"`
	Success   *bool       `json:"success,omitempty"`
}

// Result defines model for result.
type Result struct {
	Code      *int    `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Success   *bool   `json:"success,omitempty"`
}

// AgencybatchUpdateJSONRequestBody defines body for AgencybatchUpdate for application/json ContentType.
type AgencybatchUpdateJSONRequestBody = AgencyBatchUpdateRequest

// AgencyaddJSONRequestBody defines body for Agencyadd for application/json ContentType.
type AgencyaddJSONRequestBody = Agency

// AgencypagegetJSONRequestBody defines body for Agencypageget for application/json ContentType.
type AgencypagegetJSONRequestBody = AgencyPageRequest

// AgencyupdateJSONRequestBody defines body for Agencyupdate for application/json ContentType.
type AgencyupdateJSONRequestBody = AgencyUpdateRequest

// AgencygetJSONRequestBody defines body for Agencyget for application/json ContentType.
type AgencygetJSONRequestBody = AgencyQuery

// AgencyPlanbatchUpdateJSONRequestBody defines body for AgencyPlanbatchUpdate for application/json ContentType.
type AgencyPlanbatchUpdateJSONRequestBody = AgencyPlanBatchUpdateRequest

// AgencyPlanaddJSONRequestBody defines body for AgencyPlanadd for application/json ContentType.
type AgencyPlanaddJSONRequestBody = AgencyPlan

// AgencyPlangetByReferralCodeJSONRequestBody defines body for AgencyPlangetByReferralCode for application/json ContentType.
type AgencyPlangetByReferralCodeJSONRequestBody = AgencyPlanGetByReferralCodeRequest

// AgencyPlanupdateJSONRequestBody defines body for AgencyPlanupdate for application/json ContentType.
type AgencyPlanupdateJSONRequestBody = AgencyPlanUpdateRequest

// AgencyPlangetJSONRequestBody defines body for AgencyPlanget for application/json ContentType.
type AgencyPlangetJSONRequestBody = AgencyPlanQuery

// AgencyWithPlanaddJSONRequestBody defines body for AgencyWithPlanadd for application/json ContentType.
type AgencyWithPlanaddJSONRequestBody = AgencyWithPlan

// AgencyWithPlanpagegetJSONRequestBody defines body for AgencyWithPlanpageget for application/json ContentType.
type AgencyWithPlanpagegetJSONRequestBody = AgencyWithPlanPageRequest

// AgencyWithPlangetJSONRequestBody defines body for AgencyWithPlanget for application/json ContentType.
type AgencyWithPlangetJSONRequestBody = AgencyWithPlanQuery

// PlatformgetJSONRequestBody defines body for Platformget for application/json ContentType.
type PlatformgetJSONRequestBody = Platform
